### ISSUE TITLE
Problemi branch 0.1.2

### ISSUE THREAD

**Issue by DevilMat7** [black2279/bbtecweb#6]
- Aggiunta icona del sito sulla barra, se volete cambiare immagine sostituite il file favicon.ico dentro img.
- Ho risolto il problema del menù su edge ma manca da provarlo su opera vecchia versione
- Le immagini che volete mandarmi per sostituirle a camere, esterni e ristorante sono semplici da sostituire ma devono essere ridimensionate.
  La grandezza che mi è sembrata ideale è 640*480. In seguito è sufficiente sostituire il file in galleria.
- Il pulsante indietro nella galleria non mi sembra molto opportuno ma se volete posso tranquillamente aggiungerlo. Ditemi però in quale posizione.
- Non riesco a impostare la sottolineatura dei link visitati nel menù neanche forzando il css con !important, riesco solo a cambiare colore.
- Ditemi dove volete posizionare link area riservata

**Comment by black2279** [comment]
> Aggiunta icona del sito sulla barra, se volete cambiare immagine sostituite il file favicon.ico dentro img.

Ok

> Ho risolto il problema del menù su edge ma manca da provarlo su opera vecchia versione

Su IE7 non funziona, per soluzione controlla il branch cristian_v0.1

> Le immagini che volete mandarmi per sostituirle a camere, esterni e ristorante sono semplici da sostituire ma devono essere ridimensionate.
> La grandezza che mi è sembrata ideale è 640*480. In seguito è sufficiente sostituire il file in galleria.

Ok

> Il pulsante indietro nella galleria non mi sembra molto opportuno ma se volete posso tranquillamente aggiungerlo. Ditemi però in quale posizione.  

In alto a destra penso  

> Non riesco a impostare la sottolineatura dei link visitati nel menù neanche forzando il css con !important, riesco solo a cambiare colore.  

Risolvo io.  

> Ditemi dove volete posizionare link area riservata  

Nel footer (l'indirizzo è cgi-bin/login.pl)
